#!/usr/bin/env bash
# Generate MANIFEST.md index files for top-level brain directories.
# Each manifest lists all .md files with title (from frontmatter), date, and path.
# Designed for LLM two-tier retrieval: read manifest first, then fetch specific files.

set -eo pipefail

BRAIN_DIR="${BRAIN_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
DIRS=("projects" "research" "knowledge" "decisions")

generate_manifest() {
  local dir="$1"
  local manifest="$BRAIN_DIR/$dir/MANIFEST.md"

  # Collect files into array (avoids subshell from pipe)
  local files=()
  while IFS= read -r -d '' file; do
    files+=("$file")
  done < <(find "$BRAIN_DIR/$dir" -name "*.md" \
    -not -name "MANIFEST.md" -not -name "CLAUDE.md" \
    -not -name "SUMMARY.md" -not -name "README.md" -print0 | sort -z)

  {
    echo "# $dir/ - Index"
    echo ""
    echo "Auto-generated by \`docs/scripts/generate-manifests.sh\`. Do not edit manually."
    echo ""
    echo "| File | Title | Date | Tags |"
    echo "|------|-------|------|------|"

    for file in "${files[@]}"; do
      local rel_path="${file#$BRAIN_DIR/}"
      local title=""
      local date_val=""
      local tags=""

      # Extract frontmatter fields if present
      if [ "$(head -1 "$file")" = "---" ]; then
        local fm
        fm=$(awk 'NR==1{next} /^---$/{exit} {print}' "$file")
        title=$(echo "$fm" | grep -E "^title:" | head -1 | sed 's/^title:[[:space:]]*//' | sed 's/^["'"'"']//;s/["'"'"']$//' || true)
        date_val=$(echo "$fm" | grep -E "^date:" | head -1 | sed 's/^date:[[:space:]]*//' | sed 's/^["'"'"']//;s/["'"'"']$//' || true)
        tags=$(echo "$fm" | grep -E "^tags:" | head -1 | sed 's/^tags:[[:space:]]*//' | tr -d '[]' || true)
      fi

      # Fallback title from filename
      if [ -z "$title" ]; then
        local bname
        bname=$(basename "$file" .md)
        title=$(echo "$bname" | sed 's/^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-//' | tr '-' ' ')
      fi

      # Fallback date from filename
      if [ -z "$date_val" ]; then
        local bname
        bname=$(basename "$file" .md)
        date_val=$(echo "$bname" | grep -oE "^[0-9]{4}-[0-9]{2}-[0-9]{2}" || true)
      fi

      [ -z "$tags" ] && tags="-"
      [ -z "$date_val" ] && date_val="-"

      echo "| \`$rel_path\` | $title | $date_val | $tags |"
    done

    echo ""
    echo "*${#files[@]} files indexed.*"
  } > "$manifest"

  echo "  Generated $manifest (${#files[@]} files)"
}

echo "Generating MANIFEST.md files..."
for dir in "${DIRS[@]}"; do
  if [ -d "$BRAIN_DIR/$dir" ]; then
    generate_manifest "$dir"
  fi
done
echo "Done."
